#!/usr/bin/env python3
"""
Batch convert YAML page-structure files into HTML previews.

Examples:

  python convert.py
  python convert.py --input input_yaml --output output --images image-map.json
  python convert.py --input input_yaml/SEESII全品类.yaml --overwrite

The script expects image-map.json to be generated by generate_image_map.py.
"""

from __future__ import annotations

import argparse
import html
import json
import os
import sys
from pathlib import Path
from typing import Any, Iterable

try:
    import yaml
except ImportError:
    print("PyYAML is required. Install it with: pip install PyYAML", file=sys.stderr)
    raise


PAGE_NAME_KEYS = ("页面名称", "page_name", "name", "title", "名称", "标题")
MODULE_KEYS = ("包含模块", "模块", "modules", "Modules")
ELEMENT_KEYS = ("包含元素", "元素", "elements", "Elements")
DEFAULT_IMAGE_PATH = "images/default-placeholder.png"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert YAML files into HTML templates.")
    parser.add_argument(
        "--input",
        default="input_yaml",
        help="Input YAML directory or single YAML file. Default: input_yaml",
    )
    parser.add_argument(
        "--output",
        default="output",
        help="Output HTML directory. Default: output",
    )
    parser.add_argument(
        "--images",
        default="image-map.json",
        help="Path to image-map.json. Default: image-map.json",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing HTML files. Default behavior skips existing HTML.",
    )
    return parser.parse_args()


def esc(value: Any) -> str:
    return html.escape("" if value is None else str(value), quote=True)


def is_yaml_file(path: Path) -> bool:
    return path.is_file() and path.suffix.lower() in {".yaml", ".yml"}


def collect_yaml_files(input_path: Path) -> list[Path]:
    if input_path.is_file():
        if not is_yaml_file(input_path):
            raise ValueError(f"Input file is not .yaml or .yml: {input_path}")
        return [input_path]

    if not input_path.exists():
        raise FileNotFoundError(f"Input path does not exist: {input_path}")
    if not input_path.is_dir():
        raise NotADirectoryError(f"Input path is not a directory: {input_path}")

    yaml_files = [
        path
        for path in input_path.iterdir()
        if is_yaml_file(path)
    ]
    return sorted(yaml_files, key=lambda item: item.name)


def load_yaml(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as file:
        return yaml.safe_load(file)


def load_image_map(path: Path) -> dict[str, Any]:
    if not path.exists() or path.stat().st_size == 0:
        return {"default": [DEFAULT_IMAGE_PATH]}

    with path.open("r", encoding="utf-8") as file:
        data = json.load(file)

    if not isinstance(data, dict):
        raise ValueError(f"image-map.json root must be an object: {path}")

    data.setdefault("default", [DEFAULT_IMAGE_PATH])
    return data


def first_value(mapping: dict[str, Any], keys: Iterable[str], default: Any = None) -> Any:
    for key in keys:
        if key in mapping:
            return mapping[key]
    return default


def looks_like_page_list(value: Any) -> bool:
    if not isinstance(value, list):
        return False
    return any(isinstance(item, dict) and first_value(item, PAGE_NAME_KEYS) for item in value)


def find_pages(data: Any) -> list[Any]:
    if isinstance(data, list):
        return data

    if not isinstance(data, dict):
        return []

    preferred_keys = ("页面列表", "页面结构", "pages", "Pages")
    for key in preferred_keys:
        if looks_like_page_list(data.get(key)):
            return data[key]

    for value in data.values():
        if looks_like_page_list(value):
            return value

    return []


def page_name(page: Any, index: int) -> str:
    if isinstance(page, dict):
        value = first_value(page, PAGE_NAME_KEYS)
        if value:
            return str(value)
    return f"页面{index}"


def list_value(mapping: dict[str, Any], keys: Iterable[str]) -> list[Any]:
    value = first_value(mapping, keys, [])
    return value if isinstance(value, list) else []


def scalar_fields(mapping: dict[str, Any], excluded_keys: Iterable[str]) -> list[tuple[str, Any]]:
    excluded = set(excluded_keys)
    fields: list[tuple[str, Any]] = []
    for key, value in mapping.items():
        if key in excluded or isinstance(value, (dict, list)):
            continue
        fields.append((str(key), value))
    return fields


def to_relative_url(target: str | Path, base_dir: Path) -> str:
    target_path = Path(target)
    if not target_path.is_absolute():
        target_path = Path.cwd() / target_path

    try:
        rel_path = os.path.relpath(str(target_path.resolve()), str(base_dir.resolve()))
    except ValueError:
        rel_path = str(target)

    return Path(rel_path).as_posix()


def image_paths_for_page(
    image_map: dict[str, Any],
    yaml_key: str,
    page_title: str,
) -> tuple[list[str], bool]:
    yaml_images = image_map.get(yaml_key)
    if isinstance(yaml_images, dict):
        images = yaml_images.get(page_title)
        if isinstance(images, list) and images:
            return [str(item) for item in images], False

    defaults = image_map.get("default")
    if isinstance(defaults, list) and defaults:
        return [str(item) for item in defaults], True

    return [DEFAULT_IMAGE_PATH], True


def render_field_list(fields: list[tuple[str, Any]]) -> str:
    if not fields:
        return ""

    rows = [
        f"<div class=\"meta-row\"><dt>{esc(key)}</dt><dd>{esc(value)}</dd></div>"
        for key, value in fields
    ]
    return "<dl class=\"meta-list\">" + "".join(rows) + "</dl>"


def render_elements(elements: list[Any]) -> str:
    if not elements:
        return "<p class=\"muted\">未配置元素</p>"

    items: list[str] = []
    for element_index, element in enumerate(elements, start=1):
        if not isinstance(element, dict):
            items.append(f"<li class=\"element-item\"><span>{esc(element)}</span></li>")
            continue

        element_title = first_value(element, ("元素名称", "名称", "name"), f"元素 {element_index}")
        element_type = first_value(element, ("元素类型", "类型", "type"), "")
        element_fields = scalar_fields(element, excluded_keys=("元素名称", "名称", "name"))

        type_html = f"<span class=\"type-pill\">{esc(element_type)}</span>" if element_type else ""
        items.append(
            "<li class=\"element-item\">"
            f"<div class=\"element-title\"><span>{esc(element_title)}</span>{type_html}</div>"
            f"{render_field_list(element_fields)}"
            "</li>"
        )

    return "<ul class=\"element-list\">" + "".join(items) + "</ul>"


def render_modules(page: dict[str, Any]) -> str:
    modules = list_value(page, MODULE_KEYS)
    if not modules:
        return "<div class=\"module-card\"><p class=\"muted\">未配置模块</p></div>"

    rendered: list[str] = []
    for module_index, module in enumerate(modules, start=1):
        if not isinstance(module, dict):
            rendered.append(f"<section class=\"module-card\"><h3>{esc(module)}</h3></section>")
            continue

        module_title = first_value(module, ("模块名称", "名称", "name"), f"模块 {module_index}")
        module_type = first_value(module, ("模块类型", "类型", "type"), "")
        module_fields = scalar_fields(module, excluded_keys=MODULE_KEYS + ELEMENT_KEYS + ("模块名称", "名称", "name"))
        elements = list_value(module, ELEMENT_KEYS)
        type_html = f"<span class=\"type-pill\">{esc(module_type)}</span>" if module_type else ""

        rendered.append(
            "<section class=\"module-card\">"
            f"<div class=\"module-heading\"><h3>{esc(module_title)}</h3>{type_html}</div>"
            f"{render_field_list(module_fields)}"
            f"{render_elements(elements)}"
            "</section>"
        )

    return "".join(rendered)


def render_structure_panel(page: Any, index: int) -> str:
    title = page_name(page, index)
    if not isinstance(page, dict):
        return (
            "<aside class=\"structure-panel\">"
            f"<h2>{esc(index)}. {esc(title)}</h2>"
            f"<p>{esc(page)}</p>"
            "</aside>"
        )

    page_fields = scalar_fields(page, excluded_keys=MODULE_KEYS)
    return (
        "<aside class=\"structure-panel\">"
        f"<h2>{esc(index)}. {esc(title)}</h2>"
        f"{render_field_list(page_fields)}"
        f"{render_modules(page)}"
        "</aside>"
    )


def render_visual_panel(
    images: list[str],
    html_dir: Path,
    using_default: bool,
) -> str:
    image_cards: list[str] = []
    for image_index, image_path in enumerate(images, start=1):
        src = to_relative_url(image_path, html_dir)
        placeholder_class = " is-placeholder" if using_default else ""
        image_cards.append(
            f"<figure class=\"image-card{placeholder_class}\">"
            f"<img src=\"{esc(src)}\" alt=\"页面参考图 {image_index}\" loading=\"lazy\">"
            f"<figcaption>参考图 {image_index}</figcaption>"
            "</figure>"
        )

    if not image_cards:
        image_cards.append("<div class=\"empty-image-slot\">暂无图片</div>")

    return (
        "<aside class=\"visual-panel\">"
        "<div class=\"visual-heading\"><h2>页面截图</h2></div>"
        "<div class=\"image-grid\">"
        + "".join(image_cards)
        + "</div>"
        "</aside>"
    )


def render_html(
    yaml_path: Path,
    pages: list[Any],
    image_map: dict[str, Any],
    html_path: Path,
) -> str:
    yaml_key = yaml_path.stem
    html_dir = html_path.parent
    css_href = to_relative_url("styles.css", html_dir)

    page_cards: list[str] = []
    for index, page in enumerate(pages, start=1):
        title = page_name(page, index)
        images, using_default = image_paths_for_page(image_map, yaml_key, title)
        page_cards.append(
            "<section class=\"page-card\">"
            f"<header class=\"page-card-header\"><span>Page {index}</span><h1>{esc(title)}</h1></header>"
            "<div class=\"page-layout\">"
            f"{render_structure_panel(page, index)}"
            f"{render_visual_panel(images, html_dir, using_default)}"
            "</div>"
            "</section>"
        )

    if not page_cards:
        page_cards.append(
            "<section class=\"page-card\"><p class=\"muted\">未在 YAML 中找到页面列表。</p></section>"
        )

    return (
        "<!doctype html>\n"
        "<html lang=\"zh-CN\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        f"  <title>{esc(yaml_key)}</title>\n"
        f"  <link rel=\"stylesheet\" href=\"{esc(css_href)}\">\n"
        "</head>\n"
        "<body>\n"
        "  <main class=\"document-shell\">\n"
        "    <header class=\"document-header\">\n"
        f"      <h1>{esc(yaml_key)}</h1>\n"
        f"      <p>{esc(len(pages))} 个页面</p>\n"
        "    </header>\n"
        f"    {''.join(page_cards)}\n"
        "  </main>\n"
        "</body>\n"
        "</html>\n"
    )


def output_path_for_yaml(yaml_path: Path, output_root: Path) -> Path:
    return output_root / yaml_path.stem / f"{yaml_path.stem}.html"


def convert_one(
    yaml_path: Path,
    output_root: Path,
    image_map: dict[str, Any],
    overwrite: bool,
) -> tuple[str, Path | None]:
    html_path = output_path_for_yaml(yaml_path, output_root)
    if html_path.exists() and not overwrite:
        print(f"SKIP existing: {html_path}")
        return "skipped", html_path

    try:
        data = load_yaml(yaml_path)
        pages = find_pages(data)
    except Exception as exc:
        print(f"ERROR parsing {yaml_path}: {exc}", file=sys.stderr)
        return "error", None

    html_path.parent.mkdir(parents=True, exist_ok=True)
    html_text = render_html(yaml_path, pages, image_map, html_path)
    with html_path.open("w", encoding="utf-8") as file:
        file.write(html_text)

    print(f"WRITE {html_path}")
    return "written", html_path


def render_index(output_root: Path, html_paths: list[Path]) -> str:
    css_href = to_relative_url("styles.css", output_root)
    links = []
    for html_path in sorted(html_paths, key=lambda item: item.name):
        href = os.path.relpath(str(html_path.resolve()), str(output_root.resolve()))
        links.append(
            "<li>"
            f"<a href=\"{esc(Path(href).as_posix())}\">{esc(html_path.stem)}</a>"
            "</li>"
        )

    empty = "<p class=\"muted\">暂无已生成页面。</p>" if not links else ""
    return (
        "<!doctype html>\n"
        "<html lang=\"zh-CN\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        "  <title>HTML 模板索引</title>\n"
        f"  <link rel=\"stylesheet\" href=\"{esc(css_href)}\">\n"
        "</head>\n"
        "<body>\n"
        "  <main class=\"document-shell index-shell\">\n"
        "    <header class=\"document-header\">\n"
        "      <h1>HTML 模板索引</h1>\n"
        f"      <p>{esc(len(links))} 个文件</p>\n"
        "    </header>\n"
        f"    {empty}\n"
        f"    <ul class=\"index-list\">{''.join(links)}</ul>\n"
        "  </main>\n"
        "</body>\n"
        "</html>\n"
    )


def write_index(output_root: Path, html_paths: list[Path]) -> Path:
    output_root.mkdir(parents=True, exist_ok=True)
    index_path = output_root / "index.html"
    with index_path.open("w", encoding="utf-8") as file:
        file.write(render_index(output_root, html_paths))
    return index_path


def main() -> int:
    args = parse_args()
    input_path = Path(args.input)
    output_root = Path(args.output)
    image_map_path = Path(args.images)

    try:
        yaml_files = collect_yaml_files(input_path)
        image_map = load_image_map(image_map_path)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    html_paths: list[Path] = []
    stats = {"written": 0, "skipped": 0, "error": 0}

    for yaml_path in yaml_files:
        status, html_path = convert_one(yaml_path, output_root, image_map, args.overwrite)
        stats[status] += 1
        if html_path is not None:
            html_paths.append(html_path)

    index_path = write_index(output_root, html_paths)
    print(f"INDEX {index_path}")
    print(
        "Done: "
        f"{stats['written']} written, "
        f"{stats['skipped']} skipped, "
        f"{stats['error']} errors."
    )
    return 0 if stats["error"] == 0 else 2


if __name__ == "__main__":
    raise SystemExit(main())
