#!/usr/bin/env python3
"""
Organize generated HTML output into a deployable static package.

The generated deploy_package/ directory can be zipped and uploaded to Tencent
Cloud COS or another static hosting provider.

Examples:

  python organize_project.py
  python organize_project.py --input-html output --images-dir images --output deploy_package
  python organize_project.py --input-html output --images-dir images --output deploy_package --overwrite
"""

from __future__ import annotations

import argparse
import html
import os
import re
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable


IMG_SRC_RE = re.compile(r'(<img\b[^>]*?\bsrc=)(["\'])(?P<src>.*?)(\2)', re.IGNORECASE | re.DOTALL)
CSS_HREF_RE = re.compile(
    r'(<link\b[^>]*?\brel=["\']stylesheet["\'][^>]*?\bhref=)(["\'])(?P<href>.*?)(\2)',
    re.IGNORECASE | re.DOTALL,
)
HTML_EXTENSIONS = {".html", ".htm"}
IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".bmp", ".avif"}


@dataclass
class CopyStats:
    copied: int = 0
    skipped: int = 0
    missing: int = 0


@dataclass
class PackageStats:
    name: str
    html_files: set[Path] = field(default_factory=set)
    image_files: set[Path] = field(default_factory=set)
    copied_html: int = 0
    skipped_html: int = 0
    copied_images: int = 0
    skipped_images: int = 0
    missing_images: int = 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create a deployable static package from generated HTML.")
    parser.add_argument(
        "--input-html",
        default="output",
        help="HTML output directory generated by convert.py. Default: output",
    )
    parser.add_argument(
        "--images-dir",
        default="images",
        help="Images root directory. Default: images",
    )
    parser.add_argument(
        "--output",
        default="deploy_package",
        help="Deploy package root directory. Default: deploy_package",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing HTML, CSS, and image files in the deploy package.",
    )
    return parser.parse_args()


def esc(value: object) -> str:
    return html.escape("" if value is None else str(value), quote=True)


def is_html_file(path: Path) -> bool:
    return path.is_file() and path.suffix.lower() in HTML_EXTENSIONS


def is_image_file(path: Path) -> bool:
    return path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS


def collect_html_groups(input_html: Path) -> dict[str, list[Path]]:
    """
    Return a mapping of YAML-name directory -> generated HTML files.

    output/index.html is intentionally ignored. Each subdirectory under output/
    is treated as one YAML package.
    """
    if not input_html.exists():
        raise FileNotFoundError(f"HTML output directory does not exist: {input_html}")
    if not input_html.is_dir():
        raise NotADirectoryError(f"--input-html must be a directory: {input_html}")

    groups: dict[str, list[Path]] = {}
    for child in sorted(input_html.iterdir(), key=lambda item: item.name):
        if not child.is_dir():
            continue
        html_files = sorted((path for path in child.iterdir() if is_html_file(path)), key=lambda item: item.name)
        if html_files:
            groups[child.name] = html_files
    return groups


def copy_file(src: Path, dest: Path, overwrite: bool) -> str:
    """Copy one file and return copied/skipped."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists() and not overwrite:
        return "skipped"
    shutil.copy2(src, dest)
    return "copied"


def resolve_html_resource(resource: str, source_html_dir: Path) -> Path | None:
    if not resource or resource.startswith(("#", "http://", "https://", "data:", "mailto:", "tel:")):
        return None
    clean_resource = html.unescape(resource).split("#", 1)[0].split("?", 1)[0]
    if not clean_resource:
        return None

    resource_path = Path(clean_resource)
    if resource_path.is_absolute():
        return resource_path
    return (source_html_dir / resource_path).resolve()


def packaged_image_destination(source_image: Path, images_dir: Path, package_dir: Path, yaml_name: str) -> Path:
    """
    Place page images under deploy_package/<YAML>/images/.

    For images/<YAML>/xxx.png, store as images/xxx.png.
    For images/default-placeholder.png or any shared image, store by its path
    relative to images/.
    """
    images_root = images_dir.resolve()
    yaml_image_root = (images_dir / yaml_name).resolve()
    source_resolved = source_image.resolve()

    try:
        relative_inside_yaml = source_resolved.relative_to(yaml_image_root)
        return package_dir / "images" / relative_inside_yaml
    except ValueError:
        pass

    try:
        relative_inside_images = source_resolved.relative_to(images_root)
        return package_dir / "images" / relative_inside_images
    except ValueError:
        return package_dir / "images" / source_image.name


def relative_url(target: Path, base_dir: Path) -> str:
    return Path(os.path.relpath(str(target.resolve()), str(base_dir.resolve()))).as_posix()


def rewrite_css_links(html_text: str) -> str:
    def replace(match: re.Match[str]) -> str:
        href = match.group("href")
        if href.startswith(("http://", "https://", "data:")):
            return match.group(0)
        return f"{match.group(1)}{match.group(2)}styles.css{match.group(2)}"

    return CSS_HREF_RE.sub(replace, html_text)


def rewrite_and_copy_images(
    html_text: str,
    source_html_dir: Path,
    package_dir: Path,
    images_dir: Path,
    yaml_name: str,
    overwrite: bool,
) -> tuple[str, CopyStats, set[Path]]:
    stats = CopyStats()
    packaged_images: set[Path] = set()

    def replace(match: re.Match[str]) -> str:
        source_value = match.group("src")
        source_path = resolve_html_resource(source_value, source_html_dir)
        if source_path is None:
            return match.group(0)

        dest_path = packaged_image_destination(source_path, images_dir, package_dir, yaml_name)
        packaged_images.add(dest_path)

        if source_path.exists() and is_image_file(source_path):
            result = copy_file(source_path, dest_path, overwrite)
            if result == "copied":
                stats.copied += 1
            else:
                stats.skipped += 1
            new_src = relative_url(dest_path, package_dir)
            return f"{match.group(1)}{match.group(2)}{esc(new_src)}{match.group(2)}"

        stats.missing += 1
        return match.group(0)

    return IMG_SRC_RE.sub(replace, html_text), stats, packaged_images


def copy_stylesheet(package_dir: Path, overwrite: bool) -> str | None:
    stylesheet = Path("styles.css")
    if not stylesheet.exists():
        return None
    return copy_file(stylesheet, package_dir / "styles.css", overwrite)


def package_html_file(
    source_html: Path,
    package_dir: Path,
    images_dir: Path,
    yaml_name: str,
    overwrite: bool,
) -> tuple[str, CopyStats, set[Path]]:
    dest_html = package_dir / source_html.name
    html_text = source_html.read_text(encoding="utf-8")
    html_text = rewrite_css_links(html_text)
    html_text, image_stats, packaged_images = rewrite_and_copy_images(
        html_text=html_text,
        source_html_dir=source_html.parent,
        package_dir=package_dir,
        images_dir=images_dir,
        yaml_name=yaml_name,
        overwrite=overwrite,
    )

    if dest_html.exists() and not overwrite:
        return "skipped", image_stats, packaged_images

    dest_html.parent.mkdir(parents=True, exist_ok=True)
    dest_html.write_text(html_text, encoding="utf-8")
    return "copied", image_stats, packaged_images


def render_index(package_stats: Iterable[PackageStats]) -> str:
    items = []
    for stats in sorted(package_stats, key=lambda item: item.name):
        first_html = sorted(stats.html_files, key=lambda item: item.name)[0] if stats.html_files else None
        if first_html is None:
            continue
        href = f"{stats.name}/{first_html.name}"
        items.append(
            "<li>"
            f"<a href=\"{esc(href)}\">{esc(stats.name)}</a>"
            f"<span>{len(stats.html_files)} HTML / {len(stats.image_files)} images</span>"
            "</li>"
        )

    empty = "<p class=\"muted\">暂无可部署页面。</p>" if not items else ""
    return (
        "<!doctype html>\n"
        "<html lang=\"zh-CN\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        "  <title>Deploy Package</title>\n"
        "  <link rel=\"stylesheet\" href=\"styles.css\">\n"
        "</head>\n"
        "<body>\n"
        "  <main class=\"document-shell index-shell\">\n"
        "    <header class=\"document-header\">\n"
        "      <h1>Deploy Package</h1>\n"
        f"      <p>{len(items)} 个项目</p>\n"
        "    </header>\n"
        f"    {empty}\n"
        f"    <ul class=\"index-list\">{''.join(items)}</ul>\n"
        "  </main>\n"
        "</body>\n"
        "</html>\n"
    )


def write_index(output_root: Path, package_stats: list[PackageStats], overwrite: bool) -> str:
    index_path = output_root / "index.html"
    if index_path.exists() and not overwrite:
        return "skipped"
    output_root.mkdir(parents=True, exist_ok=True)
    index_path.write_text(render_index(package_stats), encoding="utf-8")
    return "copied"


def print_report(output_root: Path, package_stats: list[PackageStats]) -> None:
    print(f"Deploy package: {output_root}")
    print("Organized YAML files:")
    for stats in sorted(package_stats, key=lambda item: item.name):
        print(
            f"  - {stats.name}: "
            f"{len(stats.html_files)} HTML, "
            f"{len(stats.image_files)} images "
            f"(copied HTML {stats.copied_html}, skipped HTML {stats.skipped_html}, "
            f"copied images {stats.copied_images}, skipped images {stats.skipped_images}, "
            f"missing images {stats.missing_images})"
        )


def main() -> int:
    args = parse_args()
    input_html = Path(args.input_html)
    images_dir = Path(args.images_dir)
    output_root = Path(args.output)

    try:
        html_groups = collect_html_groups(input_html)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if not images_dir.exists() or not images_dir.is_dir():
        print(f"ERROR: images directory does not exist: {images_dir}", file=sys.stderr)
        return 1

    output_root.mkdir(parents=True, exist_ok=True)
    package_stats: list[PackageStats] = []

    for yaml_name, html_files in html_groups.items():
        package_dir = output_root / yaml_name
        stats = PackageStats(name=yaml_name)

        style_result = copy_stylesheet(package_dir, args.overwrite)
        if style_result is None:
            print("WARNING: styles.css was not found; packaged HTML will still be generated.", file=sys.stderr)

        for source_html in html_files:
            result, image_stats, packaged_images = package_html_file(
                source_html=source_html,
                package_dir=package_dir,
                images_dir=images_dir,
                yaml_name=yaml_name,
                overwrite=args.overwrite,
            )

            dest_html = package_dir / source_html.name
            stats.html_files.add(dest_html)
            stats.image_files.update(packaged_images)
            stats.copied_images += image_stats.copied
            stats.skipped_images += image_stats.skipped
            stats.missing_images += image_stats.missing

            if result == "copied":
                stats.copied_html += 1
            else:
                stats.skipped_html += 1

        package_stats.append(stats)

    root_style_result = copy_stylesheet(output_root, args.overwrite)
    if root_style_result is None:
        print("WARNING: styles.css was not found for deploy_package/index.html.", file=sys.stderr)
    write_index(output_root, package_stats, args.overwrite)
    print_report(output_root, package_stats)
    print("Done. You can zip deploy_package/ and upload it to Tencent Cloud COS.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
